-- =====================================================================
--  Everest Voucher EC – Database Initialization (PART 1/3)
--  Target: PostgreSQL 15+ (Supabase Cloud)
-- =====================================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. ENUM TYPES
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('Admin', 'Customer', 'Partner_Owner', 'Partner_Cashier'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE account_status AS ENUM ('Active', 'Inactive', 'Banned'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE partner_status AS ENUM ('Pending', 'Approved', 'Rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE banner_status AS ENUM ('Visible', 'Hidden'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE policy_type AS ENUM ('Terms_Of_Service', 'Privacy_Policy', 'Refund_Policy'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE voucher_approval_status AS ENUM ('Draft', 'Pending', 'Approved', 'Rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE voucher_display_status AS ENUM ('Visible', 'Hidden'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_status AS ENUM ('Pending', 'Paid', 'Cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE voucher_usage_status AS ENUM ('Unused', 'Used', 'Expired', 'Locked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. DROP TABLES (đảm bảo chạy lại sạch)
DROP TABLE IF EXISTS system_logs      CASCADE;
DROP TABLE IF EXISTS reviews          CASCADE;
DROP TABLE IF EXISTS issued_vouchers  CASCADE;
DROP TABLE IF EXISTS order_items      CASCADE;
DROP TABLE IF EXISTS orders           CASCADE;
DROP TABLE IF EXISTS cart_items       CASCADE;
DROP TABLE IF EXISTS voucher_branches CASCADE;
DROP TABLE IF EXISTS vouchers         CASCADE;
DROP TABLE IF EXISTS branches         CASCADE;
DROP TABLE IF EXISTS users            CASCADE;
DROP TABLE IF EXISTS partners         CASCADE;
DROP TABLE IF EXISTS policies         CASCADE;
DROP TABLE IF EXISTS banners          CASCADE;
DROP TABLE IF EXISTS categories       CASCADE;

-- 3. TABLES
CREATE TABLE categories (
    category_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    description   TEXT
);

CREATE TABLE banners (
    banner_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(150) NOT NULL,
    image_url     VARCHAR(255) NOT NULL,
    target_url    VARCHAR(255),
    display_order INT          DEFAULT 0,
    status        banner_status DEFAULT 'Visible',
    created_at    TIMESTAMPTZ  DEFAULT now()
);

CREATE TABLE policies (
    policy_id   INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_type policy_type NOT NULL,
    content     TEXT        NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE partners (
    partner_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name          VARCHAR(150) NOT NULL,
    tax_code              VARCHAR(20)  UNIQUE NOT NULL,
    business_license_url  VARCHAR(255),
    status                partner_status DEFAULT 'Pending',
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE users (
    user_id       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(100) UNIQUE NOT NULL,
    phone_number  VARCHAR(15)  UNIQUE,
    password_hash VARCHAR(255),
    full_name     VARCHAR(100) NOT NULL,
    role          user_role         DEFAULT 'Customer',
    status        account_status    DEFAULT 'Active',
    partner_id    INT         REFERENCES partners(partner_id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ DEFAULT now(),
    updated_at    TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT users_user_id_fkey_auth
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE branches (
    branch_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id   INT  NOT NULL REFERENCES partners(partner_id) ON DELETE CASCADE,
    cashier_id   UUID UNIQUE REFERENCES users(user_id) ON DELETE SET NULL,
    branch_name  VARCHAR(150) NOT NULL,
    address      VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15),
    created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE vouchers (
    voucher_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id         INT  NOT NULL REFERENCES partners(partner_id) ON DELETE CASCADE,
    category_id        INT          REFERENCES categories(category_id) ON DELETE SET NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    original_price     DECIMAL(12,2) NOT NULL,
    sale_price         DECIMAL(12,2) NOT NULL,
    total_quantity     INT NOT NULL,
    available_quantity INT NOT NULL,
    image_url          VARCHAR(255),
    start_date         TIMESTAMPTZ NOT NULL,
    end_date           TIMESTAMPTZ NOT NULL,
    expiry_days        INT NOT NULL,
    approval_status    voucher_approval_status  DEFAULT 'Draft',
    display_status     voucher_display_status   DEFAULT 'Hidden',
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT vouchers_sale_price_lt_original  CHECK (sale_price < original_price),
    CONSTRAINT vouchers_total_qty_nonneg        CHECK (total_quantity     >= 0),
    CONSTRAINT vouchers_available_qty_nonneg   CHECK (available_quantity >= 0),
    CONSTRAINT vouchers_end_after_start         CHECK (end_date  > start_date),
    CONSTRAINT vouchers_expiry_days_positive    CHECK (expiry_days > 0),
    CONSTRAINT vouchers_available_le_total      CHECK (available_quantity <= total_quantity)
);

CREATE TABLE voucher_branches (
    voucher_id INT REFERENCES vouchers(voucher_id) ON DELETE CASCADE,
    branch_id  INT REFERENCES branches(branch_id)   ON DELETE CASCADE,
    PRIMARY KEY (voucher_id, branch_id)
);

CREATE TABLE cart_items (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  UUID NOT NULL REFERENCES users(user_id)    ON DELETE CASCADE,
    voucher_id   INT  NOT NULL REFERENCES vouchers(voucher_id) ON DELETE CASCADE,
    quantity     INT  NOT NULL CHECK (quantity > 0),
    added_at     TIMESTAMPTZ DEFAULT now(),
    UNIQUE (customer_id, voucher_id)
);

CREATE TABLE orders (
    order_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    total_amount    DECIMAL(12,2) NOT NULL,
    payment_method  VARCHAR(50),
    payment_status  payment_status DEFAULT 'Pending',
    is_gift         BOOLEAN       DEFAULT FALSE,
    receiver_email  VARCHAR(100),
    gift_message    TEXT,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE order_items (
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INT  NOT NULL REFERENCES orders(order_id)   ON DELETE CASCADE,
    voucher_id    INT  NOT NULL REFERENCES vouchers(voucher_id) ON DELETE RESTRICT,
    quantity      INT  NOT NULL CHECK (quantity > 0),
    price         DECIMAL(12,2) NOT NULL
);

CREATE TABLE issued_vouchers (
    issued_voucher_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id       INT  NOT NULL REFERENCES order_items(order_item_id) ON DELETE CASCADE,
    voucher_code        VARCHAR(50) UNIQUE NOT NULL,
    status              voucher_usage_status DEFAULT 'Unused',
    valid_from          TIMESTAMPTZ NOT NULL,
    valid_to            TIMESTAMPTZ NOT NULL,
    used_at             TIMESTAMPTZ,
    used_at_branch_id   INT REFERENCES branches(branch_id) ON DELETE SET NULL,
    CONSTRAINT issued_vouchers_valid_range CHECK (valid_to > valid_from)
);

CREATE TABLE reviews (
    review_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       UUID NOT NULL REFERENCES users(user_id)         ON DELETE CASCADE,
    voucher_id        INT  NOT NULL REFERENCES vouchers(voucher_id)    ON DELETE CASCADE,
    issued_voucher_id INT  REFERENCES issued_vouchers(issued_voucher_id) ON DELETE SET NULL,
    rating            INT  NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment           TEXT,
    created_at        TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE system_logs (
    log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    UUID REFERENCES users(user_id) ON DELETE SET NULL,
    actor_role  VARCHAR(50),
    action      VARCHAR(100) NOT NULL,
    description TEXT,
    ip_address  VARCHAR(45),
    created_at  TIMESTAMPTZ DEFAULT now()
);
