-- ==========================================
-- 1. TẠO CÁC KIỂU DỮ LIỆU (ENUMS)
-- ==========================================
CREATE TYPE user_role AS ENUM ('Admin', 'Customer', 'Partner_Owner', 'Partner_Cashier');
CREATE TYPE account_status AS ENUM ('Active', 'Inactive', 'Banned');
CREATE TYPE partner_status AS ENUM ('Pending', 'Approved', 'Rejected');
CREATE TYPE banner_status AS ENUM ('Visible', 'Hidden');
CREATE TYPE policy_type AS ENUM ('Terms_Of_Service', 'Privacy_Policy', 'Refund_Policy');
CREATE TYPE voucher_approval_status AS ENUM ('Draft', 'Pending', 'Approved', 'Rejected');
CREATE TYPE voucher_display_status AS ENUM ('Visible', 'Hidden');
CREATE TYPE payment_status AS ENUM ('Pending', 'Paid', 'Cancelled');
CREATE TYPE voucher_usage_status AS ENUM ('Unused', 'Used', 'Expired', 'Locked');

-- ==========================================
-- 2. TẠO BẢNG ĐỘC LẬP (KHÔNG CÓ FOREIGN KEY)
-- ==========================================

-- Bảng CATEGORIES
CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    description TEXT
);

-- Bảng BANNERS
CREATE TABLE banners (
    banner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    target_url VARCHAR(255),
    display_order INT DEFAULT 0,
    status banner_status DEFAULT 'Visible',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng POLICIES
CREATE TABLE policies (
    policy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_type policy_type NOT NULL,
    content TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng PARTNERS
CREATE TABLE partners (
    partner_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(150) NOT NULL,
    tax_code VARCHAR(20) UNIQUE NOT NULL,
    business_license_url VARCHAR(255),
    status partner_status DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 3. TẠO BẢNG CÓ PHỤ THUỘC (FOREIGN KEYS)
-- ==========================================

-- Bảng USERS
-- Lưu ý: user_id để kiểu UUID để dễ map với auth.users của Supabase sau này
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(15) UNIQUE,
    password_hash VARCHAR(255), -- Có thể bỏ nếu dùng 100% Supabase Auth
    full_name VARCHAR(100) NOT NULL,
    role user_role DEFAULT 'Customer',
    status account_status DEFAULT 'Active',
    partner_id INT REFERENCES partners(partner_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng BRANCHES
CREATE TABLE branches (
    branch_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INT NOT NULL REFERENCES partners(partner_id) ON DELETE CASCADE,
    cashier_id UUID UNIQUE REFERENCES users(user_id) ON DELETE SET NULL,
    branch_name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng VOUCHERS
CREATE TABLE vouchers (
    voucher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INT NOT NULL REFERENCES partners(partner_id) ON DELETE CASCADE,
    category_id INT REFERENCES categories(category_id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    original_price DECIMAL(12,2) NOT NULL,
    sale_price DECIMAL(12,2) NOT NULL CHECK (sale_price < original_price),
    total_quantity INT NOT NULL CHECK (total_quantity >= 0),
    available_quantity INT NOT NULL CHECK (available_quantity >= 0),
    image_url VARCHAR(255),
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL CHECK (end_date > start_date),
    expiry_days INT NOT NULL CHECK (expiry_days > 0),
    approval_status voucher_approval_status DEFAULT 'Draft',
    display_status voucher_display_status DEFAULT 'Hidden',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng VOUCHER_BRANCHES (N-N)
CREATE TABLE voucher_branches (
    voucher_id INT REFERENCES vouchers(voucher_id) ON DELETE CASCADE,
    branch_id INT REFERENCES branches(branch_id) ON DELETE CASCADE,
    PRIMARY KEY (voucher_id, branch_id)
);

-- Bảng CART_ITEMS
CREATE TABLE cart_items (
    cart_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    voucher_id INT NOT NULL REFERENCES vouchers(voucher_id) ON DELETE CASCADE,
    quantity INT NOT NULL CHECK (quantity > 0),
    added_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (customer_id, voucher_id)
);

-- Bảng ORDERS
CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    total_amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(50),
    payment_status payment_status DEFAULT 'Pending',
    is_gift BOOLEAN DEFAULT FALSE,
    receiver_email VARCHAR(100),
    gift_message TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng ORDER_ITEMS
CREATE TABLE order_items (
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    voucher_id INT NOT NULL REFERENCES vouchers(voucher_id) ON DELETE RESTRICT,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(12,2) NOT NULL
);

-- Bảng ISSUED_VOUCHERS
CREATE TABLE issued_vouchers (
    issued_voucher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id INT NOT NULL REFERENCES order_items(order_item_id) ON DELETE CASCADE,
    voucher_code VARCHAR(50) UNIQUE NOT NULL,
    status voucher_usage_status DEFAULT 'Unused',
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ NOT NULL CHECK (valid_to > valid_from),
    used_at TIMESTAMPTZ,
    used_at_branch_id INT REFERENCES branches(branch_id) ON DELETE SET NULL
);

-- Bảng REVIEWS
CREATE TABLE reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    voucher_id INT NOT NULL REFERENCES vouchers(voucher_id) ON DELETE CASCADE,
    issued_voucher_id INT REFERENCES issued_vouchers(issued_voucher_id) ON DELETE SET NULL,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Bảng SYSTEM_LOGS
CREATE TABLE system_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
    actor_role VARCHAR(50),
    action VARCHAR(100) NOT NULL,
    description TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 4. HÀM CẬP NHẬT UPDATED_AT (Tùy chọn hữu ích)
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now(); 
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Gắn trigger cho các bảng cần thiết
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_partners_updated_at BEFORE UPDATE ON partners FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_vouchers_updated_at BEFORE UPDATE ON vouchers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();